"""Replay every language-neutral attest conformance vector under
`docs/spec/vectors/` (design §11 Fase 1, generated by `tools/gen_vectors.py`).

These vectors ARE the conformance suite: any implementation, in any
language, is attest-conformant iff it reproduces every vector's `expected.json`
exactly. This test replays them through the Python reference `verify()` —
it is a genuine check, not a tautology, because `expected.json` was authored
by hand from design §6/§11 intent (see `tools/gen_vectors.py` docstrings and
the Task 10 report), not copied from whatever `verify()` happened to return.

Vector-directory conventions (a "vector case" is any directory containing
`expected.json`, discovered recursively so multi-part vectors like
`07-unicode-canon/a-...` and `09-commitment/b-...` work uniformly):

  - `envelope.json` (a normal JSON object) XOR `envelope.raw.json` (hand-
    written bytes fed to `verify()` untouched — vector 06's genuinely
    duplicated JSON member can never round-trip through `json.load`, which
    silently keeps only the last value for a repeated key).
  - `manifests.json`: `{"manifests": {...}, "provenance": {...}, "chains":
    {...}, "artifact_manifests": {...}, "artifact_manifest_chains": {...}}`,
    built directly into a `verify.TrustStore`. The last two (G2/G3, group 31
    only, attest-versioning.md rev 4) are keyed by `work.artifact_series`
    instead of issuer — every other leaf keeps them at the empty-object
    default, same convention as `chains`.
  - `expected.json`: `signature`, `schema`, `trust` (asserted exactly);
    `revocation`/`binding` (asserted exactly when present); `ok` (asserted
    exactly when present); `errors`/`warnings` (asserted as exact lists when
    present) and/or `errors_contains`/`warnings_contains` (each substring
    must appear in at least one entry).
  - optional `disclosure.json`: the §6 step 7 buyer-binding input, either
    `{"identifier", "identifier_type", "salt_b64u"}` (salt path) or
    `{"nonce_b64u", "sig_b64u"}` (challenge path).
  - optional `manifest_pristine.json`: present only for vector 11
    (manifest-tamper) — the untampered, self-consistent manifest, checked
    directly against the tampered copy in `manifests.json` via
    `manifests.verify_key_manifest()`.
  - optional `revocation.json` (Fase 2, vectors 15/16): a single issuer-signed
    revocation record, fed to `verify()` as `revocation_view=[record]`.
    Vectors 14/14b (Fase 2) need no new file — they populate `manifests.json`'s
    already-reserved `"chains"` member instead.
  - optional `transparency.json` / `log-keys.json` / `anchor-policy.json`
    (group 28 only, Stage 2 "transparency/corroboration layer"): fed to
    `verify()` as `transparency=`/`log_keys=`/`anchor_policy=`.
    `transparency.json` is the untrusted evidence bundle verbatim (see
    `attest.transparency.evaluate_transparency`'s evidence schema).
    `log-keys.json` is a list of `{"origin", "name", "ed25519_pub_b64u",
    "mldsa_pub_b64u"}`, each turned into a `tlog.LogKey`. `anchor-policy.json`
    is `{"pinned_headers": {<hex>: {"header_hash", "merkle_root", "time"}},
    "crqc_horizon"}`, turned into an `anchor.AnchorPolicy`. All three are
    absent (and `verify()` sees `None`) for every leaf outside group 28, so
    existing leaves see zero behavior change; `expected.json` only gains the
    `transparency`/`corroboration`/`manifest_freshness` members for group 28.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from attest import anchor, canon, keys, manifests, tlog, verify

VECTORS_DIR = Path(__file__).resolve().parent.parent / "docs" / "spec" / "vectors"

_VECTOR_DIRS = sorted((p.parent for p in VECTORS_DIR.rglob("expected.json")), key=str)
_VECTOR_IDS = [str(p.relative_to(VECTORS_DIR)) for p in _VECTOR_DIRS]

_TAMPER_DIRS = [p for p in _VECTOR_DIRS if (p / "manifest_pristine.json").exists()]
_TAMPER_IDS = [str(p.relative_to(VECTORS_DIR)) for p in _TAMPER_DIRS]


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _envelope_bytes(vector_dir: Path) -> bytes:
    raw_path = vector_dir / "envelope.raw.json"
    if raw_path.exists():
        return raw_path.read_bytes()
    envelope = _load_json(vector_dir / "envelope.json")
    return json.dumps(envelope).encode("utf-8")


def _trust_store(vector_dir: Path) -> verify.TrustStore:
    data = _load_json(vector_dir / "manifests.json")
    return verify.TrustStore(
        manifests=data["manifests"],
        provenance=data["provenance"],
        chains=data.get("chains", {}),
        artifact_manifests=data.get("artifact_manifests", {}),
        artifact_manifest_chains=data.get("artifact_manifest_chains", {}),
    )


def _revocation_view(vector_dir: Path) -> list[dict[str, Any]] | None:
    path = vector_dir / "revocation.json"
    if not path.exists():
        return None
    return [_load_json(path)]


def _disclosure(vector_dir: Path) -> verify.Disclosure | None:
    path = vector_dir / "disclosure.json"
    if not path.exists():
        return None
    data = _load_json(path)
    if "salt_b64u" in data:
        return verify.Disclosure(
            identifier=data["identifier"],
            identifier_type=data["identifier_type"],
            salt=keys.b64u_decode(data["salt_b64u"]),
        )
    return verify.Disclosure(
        challenge=(keys.b64u_decode(data["nonce_b64u"]), keys.b64u_decode(data["sig_b64u"]))
    )


def _log_keys(vector_dir: Path) -> list[tlog.LogKey] | None:
    path = vector_dir / "log-keys.json"
    if not path.exists():
        return None
    return [
        tlog.LogKey(
            origin=entry["origin"],
            name=entry["name"],
            ed25519_pub=keys.b64u_decode(entry["ed25519_pub_b64u"]),
            mldsa_pub=keys.b64u_decode(entry["mldsa_pub_b64u"]),
        )
        for entry in _load_json(path)
    ]


def _anchor_policy(vector_dir: Path) -> anchor.AnchorPolicy | None:
    path = vector_dir / "anchor-policy.json"
    if not path.exists():
        return None
    data = _load_json(path)
    pinned_headers = {
        header_hash: anchor.PinnedHeader(
            header_hash=header["header_hash"],
            merkle_root=header["merkle_root"],
            time=header["time"],
        )
        for header_hash, header in data["pinned_headers"].items()
    }
    return anchor.AnchorPolicy(pinned_headers=pinned_headers, crqc_horizon=data["crqc_horizon"])


def _transparency_evidence(vector_dir: Path) -> dict[str, Any] | None:
    path = vector_dir / "transparency.json"
    if not path.exists():
        return None
    return _load_json(path)  # type: ignore[no-any-return]


@pytest.mark.parametrize("vector_dir", _VECTOR_DIRS, ids=_VECTOR_IDS)
def test_vector_matches_spec_intended_result(vector_dir: Path) -> None:
    expected = _load_json(vector_dir / "expected.json")
    envelope_bytes = _envelope_bytes(vector_dir)
    trust_store = _trust_store(vector_dir)
    disclosure = _disclosure(vector_dir)
    revocation_view = _revocation_view(vector_dir)

    result = verify.verify(
        envelope_bytes,
        trust_store,
        revocation_view=revocation_view,
        disclosure=disclosure,
        transparency=_transparency_evidence(vector_dir),
        log_keys=_log_keys(vector_dir),
        anchor_policy=_anchor_policy(vector_dir),
    )

    assert result.signature == expected["signature"]
    assert result.schema == expected["schema"]
    assert result.trust == expected["trust"]
    if "revocation" in expected:
        assert result.revocation == expected["revocation"]
    if "binding" in expected:
        assert result.binding == expected["binding"]
    if "transparency" in expected:
        assert result.transparency == expected["transparency"]
    if "corroboration" in expected:
        assert result.corroboration == expected["corroboration"]
    if "manifest_freshness" in expected:
        assert result.manifest_freshness == expected["manifest_freshness"]
    if "ok" in expected:
        assert result.ok == expected["ok"]
    if "errors" in expected:
        assert list(result.errors) == expected["errors"]
    if "warnings" in expected:
        assert list(result.warnings) == expected["warnings"]
    for substr in expected.get("errors_contains", []):
        assert any(substr in e for e in result.errors), (
            f"expected an error containing {substr!r}, got {result.errors!r}"
        )
    for substr in expected.get("warnings_contains", []):
        assert any(substr in w for w in result.warnings), (
            f"expected a warning containing {substr!r}, got {result.warnings!r}"
        )


@pytest.mark.parametrize("vector_dir", _TAMPER_DIRS, ids=_TAMPER_IDS)
def test_manifest_tamper_breaks_self_consistency(vector_dir: Path) -> None:
    """Vector 11's second, manifest-level property: the tampered manifest fed
    to `verify()` (in `manifests.json`) no longer self-verifies, while the
    untampered original (`manifest_pristine.json`) does — the concrete
    evidence that "manifest invalid" describes a self-consistency break, not
    just its downstream effect on receipt verification (covered by the
    `signature`/`errors_contains` assertions above)."""
    pristine = _load_json(vector_dir / "manifest_pristine.json")
    trust_data = _load_json(vector_dir / "manifests.json")
    tampered = trust_data["manifests"][pristine["issuer"]]

    assert manifests.verify_key_manifest(pristine) is True
    assert manifests.verify_key_manifest(tampered) is False


def test_vectors_directory_is_nonempty() -> None:
    """Guard against a silently-empty parametrize list (e.g. a wrong
    `VECTORS_DIR` path) making the whole suite above vacuously pass."""
    # 23 Fase 1/2 leaves (01-18) + 20 regression-corpus leaves (19-25, 2026-07-13)
    # + 8 hybrid conformance leaves (26, 2026-07-17) + 1 absent-valid_to
    # parity leaf (27, 2026-07-17) + 14 transparency/corroboration conformance
    # leaves (28, 2026-07-18) + 2 normative-ceiling leaves (29, 2026-07-22) +
    # 2 mixed-keyset leaves (30, 2026-07-22) + 5 manifest-currency leaves
    # (31, 2026-07-22) + 3 anchor-profile-v2 leaves (32, 2026-07-22, G4):
    # 19 a/b, 20 a-c, 21 a-g, 22 a-c, 23 a/b, 24, 25 a/b, 26 a-h, 28 a-n,
    # 29 a/c, 30 a/b, 31 a-e, 32 a-c.
    assert len(_VECTOR_DIRS) >= 78


_CANONICAL_DIRS = [p for p in _VECTOR_DIRS if (p / "canonical.json").exists()]
_CANONICAL_IDS = [str(p.relative_to(VECTORS_DIR)) for p in _CANONICAL_DIRS]


@pytest.mark.parametrize("vector_dir", _CANONICAL_DIRS, ids=_CANONICAL_IDS)
def test_payload_reserializes_to_committed_canonical_bytes(vector_dir: Path) -> None:
    """Cross-language round-trip identity, statically: the leaf ships the
    exact canonical serialization of its payload; this runner (and the TS
    conformance runner) re-serialize the parsed payload through their own
    canonical serializer and must reproduce those bytes exactly. Python
    bytes == TS bytes == committed bytes ⟹ Py→TS→Py round-trip identity
    with zero cross-runtime orchestration."""
    envelope = canon.loads_strict(_envelope_bytes(vector_dir))
    assert isinstance(envelope, dict)
    expected_bytes = (vector_dir / "canonical.json").read_bytes()
    assert canon.canonical_bytes(envelope["payload"]) == expected_bytes
