"""Replay every language-neutral attest conformance vector under
`docs/spec/vectors/` (design §11 Fase 1, generated by `tools/gen_vectors.py`).

These vectors ARE the conformance suite: any implementation, in any
language, is attest-conformant iff it reproduces every vector's `expected.json`
exactly. This test replays them through the Python reference `verify()` —
it is a genuine check, not a tautology, because `expected.json` was authored
by hand from design §6/§11 intent (see `tools/gen_vectors.py` docstrings and
the Task 10 report), not copied from whatever `verify()` happened to return.

Vector-directory conventions (a "vector case" is any directory containing
`expected.json`, discovered recursively so multi-part vectors like
`07-unicode-canon/a-...` and `09-commitment/b-...` work uniformly):

  - `envelope.json` (a normal JSON object) XOR `envelope.raw.json` (hand-
    written bytes fed to `verify()` untouched — vector 06's genuinely
    duplicated JSON member can never round-trip through `json.load`, which
    silently keeps only the last value for a repeated key).
  - `manifests.json`: `{"manifests": {...}, "provenance": {...}, "chains":
    {...}}`, built directly into a `verify.TrustStore`.
  - `expected.json`: `signature`, `schema`, `trust` (asserted exactly);
    `revocation`/`binding` (asserted exactly when present); `ok` (asserted
    exactly when present); `errors`/`warnings` (asserted as exact lists when
    present) and/or `errors_contains`/`warnings_contains` (each substring
    must appear in at least one entry).
  - optional `disclosure.json`: the §6 step 7 buyer-binding input, either
    `{"identifier", "identifier_type", "salt_b64u"}` (salt path) or
    `{"nonce_b64u", "sig_b64u"}` (challenge path).
  - optional `manifest_pristine.json`: present only for vector 11
    (manifest-tamper) — the untampered, self-consistent manifest, checked
    directly against the tampered copy in `manifests.json` via
    `manifests.verify_key_manifest()`.
  - optional `revocation.json` (Fase 2, vectors 15/16): a single issuer-signed
    revocation record, fed to `verify()` as `revocation_view=[record]`.
    Vectors 14/14b (Fase 2) need no new file — they populate `manifests.json`'s
    already-reserved `"chains"` member instead.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from attest import keys, manifests, verify

VECTORS_DIR = Path(__file__).resolve().parent.parent / "docs" / "spec" / "vectors"

_VECTOR_DIRS = sorted((p.parent for p in VECTORS_DIR.rglob("expected.json")), key=str)
_VECTOR_IDS = [str(p.relative_to(VECTORS_DIR)) for p in _VECTOR_DIRS]

_TAMPER_DIRS = [p for p in _VECTOR_DIRS if (p / "manifest_pristine.json").exists()]
_TAMPER_IDS = [str(p.relative_to(VECTORS_DIR)) for p in _TAMPER_DIRS]


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _envelope_bytes(vector_dir: Path) -> bytes:
    raw_path = vector_dir / "envelope.raw.json"
    if raw_path.exists():
        return raw_path.read_bytes()
    envelope = _load_json(vector_dir / "envelope.json")
    return json.dumps(envelope).encode("utf-8")


def _trust_store(vector_dir: Path) -> verify.TrustStore:
    data = _load_json(vector_dir / "manifests.json")
    return verify.TrustStore(
        manifests=data["manifests"],
        provenance=data["provenance"],
        chains=data.get("chains", {}),
    )


def _revocation_view(vector_dir: Path) -> list[dict[str, Any]] | None:
    path = vector_dir / "revocation.json"
    if not path.exists():
        return None
    return [_load_json(path)]


def _disclosure(vector_dir: Path) -> verify.Disclosure | None:
    path = vector_dir / "disclosure.json"
    if not path.exists():
        return None
    data = _load_json(path)
    if "salt_b64u" in data:
        return verify.Disclosure(
            identifier=data["identifier"],
            identifier_type=data["identifier_type"],
            salt=keys.b64u_decode(data["salt_b64u"]),
        )
    return verify.Disclosure(
        challenge=(keys.b64u_decode(data["nonce_b64u"]), keys.b64u_decode(data["sig_b64u"]))
    )


@pytest.mark.parametrize("vector_dir", _VECTOR_DIRS, ids=_VECTOR_IDS)
def test_vector_matches_spec_intended_result(vector_dir: Path) -> None:
    expected = _load_json(vector_dir / "expected.json")
    envelope_bytes = _envelope_bytes(vector_dir)
    trust_store = _trust_store(vector_dir)
    disclosure = _disclosure(vector_dir)
    revocation_view = _revocation_view(vector_dir)

    result = verify.verify(
        envelope_bytes, trust_store, revocation_view=revocation_view, disclosure=disclosure
    )

    assert result.signature == expected["signature"]
    assert result.schema == expected["schema"]
    assert result.trust == expected["trust"]
    if "revocation" in expected:
        assert result.revocation == expected["revocation"]
    if "binding" in expected:
        assert result.binding == expected["binding"]
    if "ok" in expected:
        assert result.ok == expected["ok"]
    if "errors" in expected:
        assert list(result.errors) == expected["errors"]
    if "warnings" in expected:
        assert list(result.warnings) == expected["warnings"]
    for substr in expected.get("errors_contains", []):
        assert any(substr in e for e in result.errors), (
            f"expected an error containing {substr!r}, got {result.errors!r}"
        )
    for substr in expected.get("warnings_contains", []):
        assert any(substr in w for w in result.warnings), (
            f"expected a warning containing {substr!r}, got {result.warnings!r}"
        )


@pytest.mark.parametrize("vector_dir", _TAMPER_DIRS, ids=_TAMPER_IDS)
def test_manifest_tamper_breaks_self_consistency(vector_dir: Path) -> None:
    """Vector 11's second, manifest-level property: the tampered manifest fed
    to `verify()` (in `manifests.json`) no longer self-verifies, while the
    untampered original (`manifest_pristine.json`) does — the concrete
    evidence that "manifest invalid" describes a self-consistency break, not
    just its downstream effect on receipt verification (covered by the
    `signature`/`errors_contains` assertions above)."""
    pristine = _load_json(vector_dir / "manifest_pristine.json")
    trust_data = _load_json(vector_dir / "manifests.json")
    tampered = trust_data["manifests"][pristine["issuer"]]

    assert manifests.verify_key_manifest(pristine) is True
    assert manifests.verify_key_manifest(tampered) is False


def test_vectors_directory_is_nonempty() -> None:
    """Guard against a silently-empty parametrize list (e.g. a wrong
    `VECTORS_DIR` path) making the whole suite above vacuously pass."""
    # 14 Fase 1 leaves (07/09 multi-part) + 9 Fase 2 leaves (14/14b + 15-16 + 17 a/b + 18).
    assert len(_VECTOR_DIRS) >= 23
