export const ATTEST_VERSION = '0.1'
export { verify, isOk } from './verify.js'
export type { VerificationResult, Disclosure } from './verify.js'
export { loadsStrict, canonicalBytes, CanonError } from './canon.js'
export type { JsonValue, JsonObject } from './canon.js'
export type { TrustStore, KeyManifest, KeyEntry } from './manifests.js'
